names:
- head
- ordinary_clothes
- person
- reflective_vest
- safety_helmet
nc: 5
path: C:\Users\22341\Project\safeyolo\yoloserver\datasets
train: dataset/images/train
val: dataset/images/val
test: dataset/images/test
